### ISSUE TITLE
apt key not seen if your OS is using an apt version older than 1.4 

### ISSUE THREAD

**Issue by meskaya** [jamesnetherton/puppet-google-chrome#37] opened 2020-08-17 15:33 UTC
It seems that #31 is breaking compatibility with OS running an apt version older than 1.4 like Ubuntu 16.04 for example running apt version 1.2

As explained here https://bugs.launchpad.net/ubuntu/+source/software-properties/+bug/1433761/comments/21 the key needs to be transformed to a binary form to be seen.
It can be done with sudo gpg --dearmor /etc/apt/trusted.gpg.d/google-chrome.asc command line.

After running above command line I can see gpg key in the result of apt-key list command:

```
/etc/apt/trusted.gpg.d/google-chrome.asc.gpg
--------------------------------------------
pub   1024D/7FAC5991 2007-03-08
uid                  Google, Inc. Linux Package Signing Key <linux-packages-keymaster@google.com>
sub   2048g/C07CB649 2007-03-08

pub   4096R/D38B4796 2016-04-12
uid                  Google Inc. (Linux Packages Signing Authority) <linux-packages-keymaster@google.com>
sub   4096R/3CB3BD13 2019-07-22 [expires: 2022-07-21]

**Comment by meskaya** [comment] 2020-08-19 14:26
We discovered this issue when we moved to version 7.4.2 of puppetlabs/apt module. 
During the installation of Ubuntu 16.04 puppet run fails with:

```
WARNING: The following packages cannot be authenticated:
google-chrome-stable
E: There were unauthenticated packages and -y was used  without --allow-unauthenticated
```

A colleague did some more testing and it seems that starting with puppetlabs/apt version 6.2.0 Ubuntu 16.04 fails to install google chrome

puppetlabs/apt (7.4.2) + jamesnetherton/google_chrome (0.8) ==> Failed
puppetlabs/apt (6.3.0) + jamesnetherton/google_chrome (0.8) ==> Failed
puppetlabs/apt (6.3.0) + jamesnetherton/google_chrome (0.6) ==> OK
puppetlabs/apt (2.4.0) + jamesnetherton/google_chrome (0.8) ==> OK
puppetlabs/apt (5.0.1) + jamesnetherton/google_chrome (0.8) ==> OK
puppetlabs/apt (6.0.0) + jamesnetherton/google_chrome (0.8) ==> OK
puppetlabs/apt (6.1.1) + jamesnetherton/google_chrome (0.8) ==> OK
puppetlabs/apt (6.2.1) + jamesnetherton/google_chrome (0.8) ==> Failed
puppetlabs/apt (6.2.0) + jamesnetherton/google_chrome (0.8) ==> Code Check Failed
puppetlabs/apt (7.5.0) + jamesnetherton/google_chrome (0.8) ==> Failed

**Comment by meskaya** [comment] 2020-08-24 12:25
I am seeing a duplicate of gnupg Package resource (Duplicate declaration: Package[gnupg] is already declared; cannot redeclare)
I guess because of apt module https://github.com/puppetlabs/puppetlabs-apt/blob/2835b79e6f8e517e51e3f1959be34d1d77b5bc15/manifests/init.pp#L318

**Comment by jamesnetherton** [comment] 2020-08-24 12:29
I guess because your puppetlabs-apt version is >= 7.0.0. Technically that's not [supported](https://github.com/jamesnetherton/puppet-google-chrome/blob/master/metadata.json#L39) by this module but I can go back and try to make it work.

**Comment by meskaya** [comment] 2020-08-24 12:33
Yes we are using 7.4.2 :)

**Comment by jamesnetherton** [comment] 2020-08-24 16:13
@meskaya Hopefully the Duplicate declaration issue is fixed now and I widened the puppetlabs-apt version range. Here's another module build to test:

[jamesnetherton-google_chrome-0.9.0.tar.gz](https://github.com/jamesnetherton/puppet-google-chrome/files/5118978/jamesnetherton-google_chrome-0.9.0.tar.gz)

**Comment by meskaya** [comment] 2020-08-25 06:56
@jamesnetherton yes the duplicate declaration issue is fixed but I am getting the "not authenticated" package issue till another apt update is done.
I am wondering if modifying "Exec['apt_update'] -> Package["${google_chrome::package_name}-${google_chrome::version}"]" to run the exec that set gpg key before apt_update can fix this issue.

**Comment by jamesnetherton** [comment] 2020-08-25 07:15
> I am wondering if modifying "Exec['apt_update'] -> Package["${google_chrome::package_name}-${google_chrome::version}"]" to run the exec that set gpg key before apt_update can fix this issue.

Yes, probably. I can check later.

If I can't get it working, then I may just revert the changes in #31 and revisit them later.

**Comment by jamesnetherton** [comment] 2020-08-25 10:57
@meskaya are you able to test again?

[jamesnetherton-google_chrome-0.9.0.tar.gz](https://github.com/jamesnetherton/puppet-google-chrome/files/5123300/jamesnetherton-google_chrome-0.9.0.tar.gz)

**Comment by meskaya** [comment] 2020-08-25 13:38
@jamesnetherton ordering doesn't seem to work :( but not 100% sure it's not something on our side overriding the ordering you are defining.

**Comment by meskaya** [comment] 2020-08-26 16:57
Hey @jamesnetherton do you think you are going to revert #31 ?

**Comment by jamesnetherton** [comment] 2020-08-26 18:16
Yeah maybe...

I’d like to try a few more things to see if I can reproduce the problem that you’re observing first. The updates that I wrote seem ok to me, so I’d like to understand why they fail if possible. If you can attach the debug output of your failed puppet run, it would be really helpful.

Otherwise, I’ll revert the changes and release tomorrow or Friday.

**Comment by jamesnetherton** [comment] 2020-08-26 18:26
Another question - would using version 0.6.0 be an option for you? That version does not contain the broken code.

**Comment by meskaya** [comment] 2020-08-26 18:38
I can go back to version 0.6 but this will break the build on another site where I can only use https protocol.

**Comment by meskaya** [comment] 2020-08-26 19:41
> Yeah maybe...
> 
> I’d like to try a few more things to see if I can reproduce the problem that you’re observing first. The updates that I wrote seem ok to me, so I’d like to understand why they fail if possible. If you can attach the debug output of your failed puppet run, it would be really helpful.
> 
> Otherwise, I’ll revert the changes and release tomorrow or Friday.

I cannot share the whole log but as you can see below after the Exec I am missing the apt update so the install fails.

```
^[[mNotice: /Stage[main]/Google_chrome::Config/Archive[/tmp/google-chrome.asc]/ensure: download archive from https://dl.google.com/linux/linux_signing_key.pub to /tmp/google-chrome.asc  with cleanup^[[0m
^[[mNotice: /Stage[main]/Google_chrome::Config/Exec[gpg -o /etc/apt/trusted.gpg.d/google-chrome.gpg --dearmor /tmp/google-chrome.asc]/returns: executed successfully^[[0m
^[[1;31mError: Execution of '/usr/bin/apt-get -q -y -o DPkg::Options::=--force-confold install google-chrome-stable' returned 100: Reading package lists...
Building dependency tree...
Reading state information...
The following additional packages will be installed:
  libvulkan1
Recommended packages:
  libu2f-udev
The following NEW packages will be installed:
  google-chrome-stable libvulkan1
0 upgraded, 2 newly installed, 0 to remove and 1 not upgraded.
Need to get 70.3 MB of archives.
After this operation, 237 MB of additional disk space will be used.
WARNING: The following packages cannot be authenticated!
  google-chrome-stable
E: There were unauthenticated packages and -y was used without --allow-unauthenticated^[[0m
^[[1;31mError: /Stage[main]/Google_chrome::Install/Package[google-chrome-stable]/ensure: change from 'purged' to 'present' failed: Execution of '/usr/bin/apt-get -q -y -o DPkg::Options::=--force-confold install google-chrome-stable' returned 100: Reading package lists...
Building dependency tree...
Reading state information...
The following additional packages will be installed:
  libvulkan1
Recommended packages:
  libu2f-udev
The following NEW packages will be installed:
  google-chrome-stable libvulkan1
0 upgraded, 2 newly installed, 0 to remove and 1 not upgraded.
Need to get 70.3 MB of archives.
After this operation, 237 MB of additional disk space will be used.
WARNING: The following packages cannot be authenticated!
  google-chrome-stable
E: There were unauthenticated packages and -y was used without --allow-unauthenticated^[[0m

**Comment by jamesnetherton** [comment] 2020-08-27 07:18
@meskaya please can you try one last time:

[jamesnetherton-google_chrome-0.9.0.tar.gz](https://github.com/jamesnetherton/puppet-google-chrome/files/5134438/jamesnetherton-google_chrome-0.9.0.tar.gz)

**Comment by meskaya** [comment] 2020-08-27 11:39
@jamesnetherton I have found out an issue on our side. Puppet environment was not refreshed :(
So, with previous version I have a dependency cycle

```
Found 1 dependency cycle:
(Archive[/tmp/google-chrome.asc] => Exec[gpg -o /etc/apt/trusted.gpg.d/google-chrome.gpg --dearmor /tmp/google-chrome.asc] => Apt::Source[google-chrome] => Apt::Setting[list-google-chrome] => File[/etc/apt/sources.list.d/google-chrome.list] => Class[Apt::Update] => Exec[apt_update] => Class[Apt::Update] => Package[gnupg] => Archive[/tmp/google-chrome.asc])\nTry the '--graph' option and opening the resulting '.dot' file in OmniGraffle or GraphViz
```
I will try with your last version too

**Comment by meskaya** [comment] 2020-08-28 07:37
Still no luck with ordering. At least the build is not stopped and Google Chrome is installed later in the build when something else triggers an apt update.

**Comment by jamesnetherton** [comment] 2020-08-28 08:14
I reverted #31. Here's the module I'm proposing to upload to the forge:

[jamesnetherton-google_chrome-0.9.0.tar.gz](https://github.com/jamesnetherton/puppet-google-chrome/files/5140878/jamesnetherton-google_chrome-0.9.0.tar.gz)

**Comment by meskaya** [comment] 2020-08-28 08:16
Thanks @jamesnetherton 
I will test it as soon as possible

**Comment by meskaya** [comment] 2020-08-28 09:54
@jamesnetherton  All good now :+1:

**Comment by jamesnetherton** [comment] 2020-08-28 10:12
@meskaya 0.9.0 has been published on the Puppet Forge. Thanks for your help with testing :1st_place_medal:

I still find odd that the original fixes did not work for you. From my perspective, the puppetlabs-apt module is fundamentally broken in terms of how it manages apt update and proxy server configuration. They expect every module to implement hacks to work around these problems:

https://tickets.puppetlabs.com/browse/MODULES-2190
https://github.com/puppetlabs/puppetlabs-apt#limitations

**Closed by jamesnetherton** 2020-08-28 10:12 UTC
